-- ============================================================================
-- Naselja: every settlement, village and town quarter in BiH (about 19 500 places)
--
-- Before: a job or profile location could only be one of ~90 towns, so "Otes" and "Hrasnica" were both
-- just "Ilidža" (or "Sarajevo"), and the reach rule measured from the town centre.
-- After: a location can be any settlement, stored as its label "Naselje, Općina" ("Otes, Ilidža",
-- "Hrasnica, Ilidža", "Otes, Kakanj"); the reach rule, matching, the recommended feed and radius search
-- measure from the settlement's own point. Old town-only values ("Sarajevo", "Tuzla") keep their old
-- point and keep working.
--
-- Distances stay haversine (public.distance_km) with a latitude/longitude box first, like
-- performance/01_search_radius_first.sql: PostGIS is not installed on this project and within one country
-- the answer is the same.
--
-- Data: supabase/locations/bih_locations.csv, built from Who's On First / GeoNames (CC BY 4.0) by
-- scripts/locations/build-bih-locations.mjs; 02_seed_bih_locations.sql (generated by
-- scripts/locations/seed-bih-locations.mjs) fills the table.
-- Needs migration_search_ranking (fold_text, distance_km, city_coords, coords_for_location) and
-- airtasker/04 (listing_reach_km). Safe to run more than once.
-- ============================================================================

-- fold_text, plus "dj" → "d", so "Djurdjevik", "Durdevik" and "Đurđevik" are the same word
create or replace function public.fold_loose(p text)
returns text language sql immutable parallel safe strict set search_path = public as $$
  select replace(regexp_replace(btrim(public.fold_text(p)), '\s+', ' ', 'g'), 'dj', 'd');
$$;

create table if not exists public.bih_locations (
  id bigint generated always as identity primary key,
  settlement_name text not null,                         -- naselje: "Otes"
  municipality text not null,                            -- općina / grad: "Ilidža"
  region_canton text,                                    -- kanton, "Republika Srpska" or "Brčko distrikt"
  postal_code text,                                      -- not in the open data yet; filled when we have it
  kind text not null default 'naselje' check (kind in ('grad', 'naselje', 'dio grada')),
  population integer not null default 0,
  lat double precision not null check (lat between 42.4 and 45.4),
  lng double precision not null check (lng between 15.6 and 19.8),
  label text not null,                                   -- what jobs and profiles store: "Otes, Ilidža"
  source text,                                           -- wof:<id> or "dopuna" (added by hand)
  label_key text generated always as (public.fold_loose(label)) stored,
  name_key text generated always as (public.fold_loose(settlement_name)) stored,
  search_tsv tsvector generated always as (to_tsvector('simple', public.fold_loose(settlement_name || ' ' || municipality))) stored
);

comment on table public.bih_locations is
  'Naselja u BiH (Who''s On First / GeoNames, CC BY 4.0). label = "Naselje, Općina" is what listings.location and profiles.city store.';

create unique index if not exists bih_locations_label_key_idx on public.bih_locations (label_key);
-- typing "Ote…" / "hrasnica ili…": full-text over name + municipality (GIN) …
create index if not exists bih_locations_search_idx on public.bih_locations using gin (search_tsv);
-- … prefix and typo-tolerant name matches (trigram GIN serves both LIKE 'ote%' and similarity)
create index if not exists bih_locations_name_trgm_idx on public.bih_locations using gin (name_key extensions.gin_trgm_ops);
create index if not exists bih_locations_geo_idx on public.bih_locations (lat, lng);

alter table public.bih_locations enable row level security;
drop policy if exists bih_locations_read on public.bih_locations;
create policy bih_locations_read on public.bih_locations for select using (true);
revoke insert, update, delete, truncate on public.bih_locations from anon, authenticated;
grant select on public.bih_locations to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Type-ahead: "ote" → Otes, Ilidža · Otes, Kakanj · …   "otes, kak" → Otes, Kakanj
-- Exact name first, then names that start with what was typed, then any word of name or municipality
-- that starts with it, then close spellings (3+ letters). Towns before villages, bigger before smaller.
-- ---------------------------------------------------------------------------
create or replace function public.search_locations(p_query text, p_limit integer default 8)
returns table(id bigint, label text, settlement_name text, municipality text, region_canton text, kind text, lat double precision, lng double precision)
language sql stable parallel safe set search_path = public, extensions
as $$
  with q as (
    select public.fold_loose(split_part(coalesce(p_query, ''), ',', 1)) as name,
           public.fold_loose(split_part(coalesce(p_query, ''), ',', 2)) as muni,
           least(greatest(coalesce(p_limit, 8), 1), 20) as lim
  ),
  t as (
    select q.*,
      nullif(array_to_string(array(
        select w || ':*' from regexp_split_to_table(regexp_replace(q.name, '[^a-z0-9 ]', ' ', 'g'), '\s+') w where w <> ''
      ), ' & '), '') as words
    from q
  ),
  hits as (
    select l.*,
      case when l.name_key = t.name then 0
           when l.name_key like t.name || '%' then 1
           when t.words is not null and l.search_tsv @@ to_tsquery('simple', t.words) then 2
           else 3 end as tier,
      similarity(l.name_key, t.name) as sim
    from public.bih_locations l, t
    where length(t.name) >= 2
      and (l.name_key like t.name || '%'
           or (t.words is not null and l.search_tsv @@ to_tsquery('simple', t.words))
           or (length(t.name) >= 3 and l.name_key % t.name))
      and (t.muni = '' or public.fold_loose(l.municipality) like t.muni || '%')
  )
  select h.id, h.label, h.settlement_name, h.municipality, h.region_canton, h.kind, h.lat, h.lng
  from hits h, t
  order by h.tier, (h.kind = 'grad') desc, h.population desc, h.sim desc, length(h.settlement_name), h.label
  limit (select lim from t);
$$;

revoke execute on function public.search_locations(text, integer) from public;
grant execute on function public.search_locations(text, integer) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Location text → point. Order: an old town name exactly (its point never moves), then a settlement label
-- exactly ("Otes, Ilidža"), then the first old town contained in free text (as before).
-- Everything that measures distance (listing_reach, guard_bid_reach, recommended_listings, matching)
-- goes through this, so settlements work there without other changes.
-- ---------------------------------------------------------------------------
create or replace function public.coords_for_location(p_location text)
returns table(lat double precision, lng double precision) language sql stable parallel safe set search_path = public as $$
  with f as (select public.fold_text(coalesce(p_location, '')) as t, public.fold_loose(coalesce(p_location, '')) as k)
  select x.lat, x.lng from (
    select c.lat, c.lng, 0 as pri, 0 as len from public.city_coords c, f where f.t <> '' and c.folded = f.t
    union all
    select b.lat, b.lng, 1, 0 from public.bih_locations b, f where f.k <> '' and b.label_key = f.k
    union all
    select c.lat, c.lng, 2, -length(c.folded) from public.city_coords c, f where f.t <> '' and f.t like '%' || c.folded || '%'
  ) x
  order by x.pri, x.len
  limit 1;
$$;

-- A job saved with a settlement label gets that settlement's point, whatever the app sent (older app
-- versions only know towns and would send the municipality's centre).
create or replace function public.listing_settlement_point()
returns trigger language plpgsql set search_path = public as $$
declare p record;
begin
  if tg_op = 'UPDATE' and new.location is not distinct from old.location then return new; end if;
  select b.lat, b.lng into p from public.bih_locations b
  where b.label_key = public.fold_loose(coalesce(new.location, ''))
    and not exists (select 1 from public.city_coords c where c.folded = public.fold_text(btrim(new.location)));
  if found then new.lat := p.lat; new.lng := p.lng; end if;
  return new;
end $$;

revoke execute on function public.listing_settlement_point() from public, anon, authenticated;
drop trigger if exists listings_settlement_point on public.listings;
create trigger listings_settlement_point
  before insert or update of location on public.listings
  for each row execute function public.listing_settlement_point();

-- ---------------------------------------------------------------------------
-- Jobs near a place: published, in-person jobs around a settlement (by label) or a point.
-- p_radius_km given → that fixed radius. Not given → each job's own reach (what it pays: 15 km under
-- 50 KM … all of BiH from 800 KM), the same rule the database enforces on offers.
-- A job in Otes is found from Stup (about 1 km), not from Bihać (about 200 km).
-- ---------------------------------------------------------------------------
create or replace function public.jobs_near_location(
  p_location text default null, p_lat double precision default null, p_lng double precision default null,
  p_radius_km double precision default null, p_limit integer default 50)
returns table(id uuid, title text, category text, location text, price numeric, currency text, created_at timestamptz,
              lat double precision, lng double precision, distance_km double precision, reach_km numeric)
language sql stable security definer set search_path = public
as $$
  with origin as (
    select coalesce(p_lat, c.lat) as lat, coalesce(p_lng, c.lng) as lng
    from (select 1) one left join lateral public.coords_for_location(p_location) c on p_lat is null
  ),
  box as (
    -- without a fixed radius the widest reach below "all of BiH" (120 km) bounds the box; 800 KM+ jobs
    -- (no limit) are let through separately
    select o.lat, o.lng, coalesce(p_radius_km, 120) as km,
           coalesce(p_radius_km, 120) / 111.32 as lat_span,
           coalesce(p_radius_km, 120) / (111.32 * greatest(cos(radians(o.lat)), 0.01)) as lng_span
    from origin o where o.lat is not null and o.lng is not null
  ),
  near as (
    select l.id, l.title, l.category, l.location, l.price, l.currency, l.created_at, l.lat, l.lng,
           public.distance_km(b.lat, b.lng, l.lat, l.lng) as d,
           public.listing_reach_km(l.price, l.travel_allowance) as reach
    from public.listings l cross join box b
    where l.status = 'published'
      and l.invited_provider is null
      and (l.due_date is null or l.due_date >= public.today_ba())
      and l.lat is not null and l.lng is not null
      and not public.listing_is_remote(l.location)
      and ((l.lat between b.lat - b.lat_span and b.lat + b.lat_span and l.lng between b.lng - b.lng_span and b.lng + b.lng_span)
           or (p_radius_km is null and public.listing_reach_km(l.price, l.travel_allowance) is null))
  )
  select n.id, n.title, n.category, n.location, n.price, n.currency, n.created_at, n.lat, n.lng,
         round(n.d::numeric, 1)::double precision, n.reach
  from near n
  where case when p_radius_km is not null then n.d <= p_radius_km
             else n.reach is null or n.d <= n.reach end
  order by n.d, n.created_at desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200);
$$;

revoke execute on function public.jobs_near_location(text, double precision, double precision, double precision, integer) from public;
grant execute on function public.jobs_near_location(text, double precision, double precision, double precision, integer) to anon, authenticated;
