/** Query keys only (no service imports) — safe to import from the entry bundle (tab bar badges). */
export const keys = {
  search: (params) => ['search', params],
  listing: (id) => ['listing', id],
  listingExtras: (id) => ['listing', id, 'extras'],
  related: (id) => ['listing', id, 'related'],
  suggested: (id) => ['listing', id, 'suggested'],
  myBundle: (userId) => ['me', userId, 'bundle'],
  myListings: (userId) => ['me', userId, 'listings'],
  myBids: (userId) => ['me', userId, 'bids'],
  inbox: (userId) => ['me', userId, 'inbox'],
  thread: (conversationId) => ['thread', conversationId],
  notifications: (userId) => ['me', userId, 'notifications'],
  unreadNotifications: (userId) => ['me', userId, 'unread-notifications'],
  unreadMessages: (userId) => ['me', userId, 'unread-messages'],
  recommended: (userId) => ['me', userId, 'recommended'],
  taste: (userId) => ['me', userId, 'taste'],
  feedPool: (limit) => ['feed', 'latest', limit],
  providerPool: (categories) => ['feed', 'providers', categories],
  publicProfile: (userId) => ['profile', userId],
  savedIds: (userId) => ['me', userId, 'saved-ids'],
  savedListings: (userId) => ['me', userId, 'saved'],
  offerGate: (userId) => ['me', userId, 'offer-gate'],
  credentials: (userId) => ['me', userId, 'credentials'],
  offerReach: (userId, listingId) => ['me', userId, 'offer-reach', listingId],
  quoteRequests: (userId) => ['me', userId, 'quote-requests'],
  quoteRequestsEnabled: ['feature', 'quote-requests'],
  badgeCatalog: ['badges', 'catalog'],
  badgeVault: (userId) => ['me', userId, 'badge-vault'],
  jobConditionsEnabled: ['feature', 'job-conditions'],
  // izdvojeni oglasi (Hitno / VIP) i ploča izvođača
  promoted: (params) => ['search', 'promoted', params],
  promotionOptions: (userId) => ['me', userId || 'guest', 'promotion-options'],
  providerPayments: (userId) => ['me', userId, 'provider-payments'],
}
